### ISSUE TITLE
Unable to deserialize U256 with custom endianness in JSON

### ISSUE THREAD

**Issue by stanislav-tkach** [nlordell/ethnum-rs#27]
Unless I'm missing something, the `ethnum::serde::bytes::le`, `ethnum::serde::bytes::be` and `ethnum::serde::bytes::ne` attributes cannot really be used with the `U256` type. The serialization works properly, but the deserialization gives the "invalid type: sequence, expected 32 bytes in little endian" error. As far as I can see, `serde::de::Visitor::visit_seq` is called, but only the `visit_bytes` method is implemented for `BytesVisitor`.

Here is the minimal reproducible example:
```rust
extern crate ethnum;

#[test]
fn u256_deserialize() {
    #[derive(serde::Serialize, serde::Deserialize)]
    struct Test {
        // Any of the following attributes would give an error during deserialization.
        //#[serde(with = "ethnum::serde::bytes::le")]
        //#[serde(with = "ethnum::serde::bytes::be")]
        #[serde(with = "ethnum::serde::bytes::ne")]
        index: ethnum::U256,
    }

    let test = Test {
        index: ethnum::U256::new(1),
    };
    let serialized = serde_json::to_string(&test).unwrap();
    let _deserialized: Test = serde_json::from_str(&serialized).unwrap();
}
```

**Comment by nlordell** [comment]
Thanks for the detailed write-up, and sorry for taking so long to get back to you, I must have missed the notification somehow.

**Comment by nlordell** [comment]
Interesting, so my understanding of `serde` is that, for byte arrays you are meant to use `visit_bytes`. AFAIU, JSON doesn't really have a "bytes" primitive (which is why I wouldn't expect the `ethnum::serde::bytes::*` serialization overrides to work with JSON).

That being said, if `ethnum::serde::bytes::*` would be useful for sequences as well (i.e. a JSON array of 32-elements), then I would be fine with adding support for it (although it feels slightly counterintuitive to me).

**Comment by nlordell** [comment]
It looks like the doc-comments advertises that it should work like this and I just forgot about it 🙈.
