### ISSUE TITLE
wish a new version be released

### ISSUE THREAD

**Issue by davidli2010** [nlordell/ethnum-rs#6]
I'm looking forward v1.0.4 be released with #2

**Comment by nlordell** [comment]
Sure... I actually wanted to release `1.1.0` with signed integer support.

Here is the branch I was working off of: https://github.com/nlordell/ethnum-rs/tree/signed just need to finish it off.

**Comment by davidli2010** [comment]
Yes, I need a 1.0.4.

**Comment by nlordell** [comment]
https://crates.io/crates/ethnum/1.0.4

**Comment by sbeckeriv** [comment]
Just a follow up to this release. It introduced a breaking change to my build. I am unsure if anything can be done now but if someone finds this you can run `cargo update -p ethnum --precise 1.0.3` to lock in 1.0.3. I think a 1.1.0 version would have prevented this issue for me.

How it happened? I ran `cargo update` for reasons. I am using `decimal-rs`.  It updated ethnum as well. I needed rollback to an early version of  `decimal-rs` that was not updated for 1.0.4. I realize that if decimal-rs had a hard cap on versions this might also have fixed the issue.  The error from my build: 
```
rror[E0425]: cannot find function `mulddi3` in module `ethnum::intrinsics`
   --> /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/decimal-rs-0.1.14/src/u256.rs:401:34
    |
401 |         U256(ethnum::intrinsics::mulddi3(&left, &right))
    |                                  ^^^^^^^ help: a function with a similar name exists: `umulddi3`
    |
   ::: /home/becker/.cargo/registry/src/github.com-1ecc6299db9ec823/ethnum-1.0.4/src/intrinsics/native/mul.rs:14:1
    |
14  | pub fn umulddi3(a: &u128, b: &u128) -> U256 {
    | ------------------------------------------- similarly named function `umulddi3` defined here
```

This was more of an FYI if someone else finds this. Thank you nlordell for your time on this code and reading this message!

Becker

**Comment by nlordell** [comment]
Hey @sbeckeriv, I'm sorry that the release broke your builds 🙈.

Just a little bit of context: I've been working on adding support for [`signed`](https://github.com/nlordell/ethnum-rs/tree/signed) integers to this crate. Because of this, the intrinsics need to differentiate between signed and unsigned operations in some cases (specifically, multiplication/division and overflowing addition/subtraction).

I had considered following semver (which, from my understanding, would have required a version bump to `2.0.0`). I decided against that and instead added some notes about the stability of the `intrinsics` API (note that this is **not** in `main`, sorry!):

https://github.com/nlordell/ethnum-rs/blob/183bafb58964c5581c876be781d6762bd2bdbdd1/src/intrinsics.rs#L4-L10

I think, moving forward I will add more information about this in the README so it is more obvious. That being said, the `intrinsics` module was not intended to have a stable API, since they are "implementation details" of the 256-bit integer implementation and subject to change when refactoring. They were originally provided "as-is" just to have a more direct access to the low-level API when needed - specifically I thought it could be useful when compiling with the `intrinsics` feature to get direct access to the LLVM-generated operation implementations.

Again, I'm sorry about breaking your builds! I will add more info so others don't run into the same issues.

**Comment by nlordell** [comment]
Note that in your particular case, the `u128 × u128 => u256` intrinsic was renamed to `umulddi3`.

**Comment by nlordell** [comment]
@sbeckeriv Added this section to the README: https://github.com/nlordell/ethnum-rs#api-stability
